const CardContent = [
  {
    id: 1,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 2,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 3,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 4,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 5,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 6,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 7,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 8,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
  {
    id: 9,
    title: "Manajemen Uang Pribadi",
    image: "",
    deskripsi: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, eligendi!,",
    dosen: "Prof. Dr. Khong Guan, S5 tank",
    kelas: "Satuan",
    waktu: "4 Minggu",
    harga: "150.000",
    link: "#",
  },
];

export default CardContent;
